version: "3.9"
services:
  rag-api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./vectorstore:/app/vectorstore
    restart: unless-stopped
